/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.cts.passengerservice.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import com.cts.passengerservice.model.UpdatePhoneFault;
import com.cts.passengerservice.model.UpdatePhoneRequest;
import com.cts.passengerservice.model.UpdatePhoneResponse;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-01-22T06:44:04.663Z")

@Api(value = "updatePhone", description = "the updatePhone API")
public interface UpdatePhoneApi {

    @ApiOperation(value = "Operation UpdatePhone", notes = "", response = UpdatePhoneResponse.class, tags={ "Passenger", })
    @ApiResponses(value = { 
        @ApiResponse(code = 500, message = "", response = UpdatePhoneFault.class),
        @ApiResponse(code = 200, message = "", response = UpdatePhoneResponse.class) })
    
    @RequestMapping(value = "/updatePhone",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/xml", "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<UpdatePhoneResponse> updatePhone(@ApiParam(value = "" ,required=true )  @Valid @RequestBody UpdatePhoneRequest body);

}
